server:
  port: 82

spring:
  application:
    name: cloud-consumer-order-consul
  cloud:
    consul:
      host: localhost # consul注册中心地址
      port: 8500
      discovery:
        hostname: 127.0.0.1
        service-name: ${spring.application.name}



