server:
  port: 80

spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1 # 采集率介于0到1之间，1表示全部采集

eureka:
  client:
    register-with-eureka: true # true表示不是否将自己注册进EurekaServer，默认是true
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka/ # （单机注册中心）设置与eureka server交互的地址，查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ # （集群注册中心）设置与eureka server交互的地址，查询服务和注册服务都需要依赖这个地址

