server:
  port: 83

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true # true表示不是否将自己注册进EurekaServer，默认是true
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka/ # （单机注册中心）设置与eureka server交互的地址，查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ # （集群注册中心）设置与eureka server交互的地址，查询服务和注册服务都需要依赖这个地址

# 设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.xwl.springcloud.service.PaymentOpenFeignService: debug

