server:
  port: 3344
spring:
  application:
    name: cloud-config-center # 服务名，即注册进eureka注册中心的名字
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xuwulin/springcloud2020-study-config.git # git地址
          search-paths: # 搜索目录
            - springcloud-config
      label: master # 读取分支
  rabbitmq: #mq相关配置
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
# rabbitmq相关配置，暴露bus刷新点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'