server:
  port: 8001

spring:
  application:
    name: cloud-payment-service # 服务名称
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1 # 采集率介于0到1之间，1表示全部采集
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud2020-study?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

eureka:
  client:
    register-with-eureka: true # true表示不是否将自己注册进EurekaServer，默认是true
    fetchRegistry: true # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配好ribbon使用负载均衡
    service-url:
#      defaultZone: http://localhost:7001/eureka/ # （单机注册中心）设置与eureka server交互的地址，查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ # （集群注册中心）设置与eureka server交互的地址，查询服务和注册服务都需要依赖这个地址
  instance:
    instance-id: payment8001 # 实例id，如果不配置，则会在服务列表中显示主机名
    prefer-ip-address: true # 当鼠标移动到服务列表中的服务名上时，显示IP地址
#    lease-renewal-interval-in-seconds: 1 # Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认是30秒）
#    lease-expiration-duration-in-seconds: 2 # Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认90秒），超时将剔除服务

mybatis:
  mapper-locations: classpath:mapper/*.xml # 扫描mapper
  type-aliases-package: com.xwl.springcloud.entities # 所有Entity别名类所在包
