server:
  port: 8003

spring:
  application:
    name: cloud-payment-service # 服务名称==>注册到zookeeper注册中的名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud2020-study?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    zookeeper:
      connect-string: 192.168.92.130:2181 # 默认localhost:2181

mybatis:
  mapper-locations: classpath:mapper/*.xml # 扫描mapper
  type-aliases-package: com.xwl.springcloud.entities # 所有Entity别名类所在包

